/**
 * API de Libros en MongoDB
 * Api Rest de Ejemplo con Libros
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pepesan@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export class Libro {
    constructor(
        public _id?: string,
        public titulo?: string,
        public autor?: string,
        public isbn?: string,
    )
    {
        this.titulo="";
        this.autor="";
        this.isbn="";
    }

}
