version: '2'
services:
  frontend:
    build: ./frontend
    #command: npm start
    volumes:
      - /data/www
      - /etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - backend
    #environment:
      # DATABASE_URL: mongodb://mongo:27017/user
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/user
  mongo:
    image: mongo:4.0.6
    ports:
      - "27017:27017"
