version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://localhost:27027/user
  mongo:
    image: mongo:4.0.6
    ports:
      - "27017:27017"
